trigger:
  branches:
    exclude:
      - master
  paths:
    exclude:
      - README.org

pr:
  paths:
    exclude:
      - README.org

strategy:
  matrix:
    vs2017-win2016:
      IMAGE_NAME: 'vs2017-win2016'

pool:
  vmImage: $(IMAGE_NAME)

steps:
- checkout: self
- template: steps/setup-emacs.yml
- template: steps/setup-cask.yml
- template: steps/test.yml
