name: CI

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.rst'
  push:
    paths-ignore:
    - '**.md'
    - '**.rst'
    branches-ignore:
    - 'master'
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # beginning of time is 24.3 when cl-flet was defined
        emacs_version: [24.3, 24.4, 24.5, 25.3, 26.3, 27.1, snapshot]
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: paths
      run: |
        echo "$HOME/local/bin" >> $GITHUB_PATH
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$HOME/.local/lib" >> $GITHUB_ENV
    - run: 'make test'
      continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
